### ISSUE TITLE
Allow button disabled on the screen "realm browser needs access to this path"

### ISSUE THREAD

**Issue by jpsim** [realm/realm-browser-osx#109]
> Title says it all. I am trying to open a default.realm file and the window says the browser needs access, press allow to continue, but the Allow button is disabled.

Originally posted by @pvencill in realm-cocoa: https://github.com/realm/realm-cocoa/issues/2903

**Comment by TimOliver** [comment]
Hi @pvencill!

Sorry to hear you're having an issue with the sandboxing dialog in the Browser. That particular window is required by Apple since the user needs to grant permission to the folder that the Realm file is located in, in order to be able to open it.

I've never seen it disabled before, but my guess would be that somehow, it wasn't able to work out which folder your Realm file is in on its own, so it's waiting for you to manually click on the Realm's parent folder.

If I may ask, where is the Realm file you're trying to open located? Is it in a relatively normal location on your Mac?

**Comment by TimOliver** [comment]
In my testing on the Realm Browser yesterday, I came across this problem as well. I was trying to open up a Realm file that was located in my Mac's temporary directory (generated by Realm Browser's unit tests), and the 'Allow' button was disabled. This seems like an intentional policy on Apple's behalf to stop third party apps messing with certain system locations.

I came up with 2 potential workarounds:
* If I drilled up one extra level in the folder hierarchy, the 'Allow' button became enabled again. This will allow the folder to be successfully opened (Sandboxing only requires a parent directory at any level to have permission given; it's not absolutely necessary for the immediate folder to be given permission.)
* I could just copy and paste the Realm file to a more user-accessible location (like my Desktop) and open it from there.

In any case, as that dialog itself is an explicitly Apple-managed window, there's nothing directly we can to modify the behaviour of the 'Allow' button otherwise.

I hope this helped!
