### ISSUE TITLE
Realm Browser plugin not launchable through Xcode 7.3

### ISSUE THREAD

**Issue by KMKRN** [realm/realm-browser-osx#160]
I've tried the manual installation and also Alcatraz, but I don't see the option to launch Realm Browser from Xcode. Here's what I'm supposed to see:

<img width="542" alt="ss" src="https://cloud.githubusercontent.com/assets/7746223/15248920/07c3e54a-191d-11e6-9150-6a01a237561a.png">

But I don't really see it there, although Alcatraz shows the RB is installed.

<img width="363" alt="screen shot 2016-05-13 at 15 05 52" src="https://cloud.githubusercontent.com/assets/7746223/15248938/2630158a-191d-11e6-8f14-da51bc4877be.png">

P.S. I'm not sure it has anything to do with Alcatraz because the Realm Plugin is working.

**Comment by TimOliver** [comment]
Hi @KMKRN!

I just had a quick look. That particular plugin in that screenshot that opened the Realm Browser was [a third party one](https://github.com/kittinunf/RealmBrowser-Plugin), not maintained by Realm.

The developer seems to have since deprecated that plugin (Explaining why it stopped working in Xcode.) in favour of the features they directly contributed to the Realm plugin, but it looks like that didn't include the ability to simply open the Browser from Xcode (I'm guessing because they thought it was redundant).

Either way, the Realm Plugin itself is maintained and tracked in [the main Realm Cocoa repo](https://github.com/realm/realm-cocoa/tree/master/plugin), whereas this repo is just for the Browser's codebase. If you want, raise an issue there proposing this for the plugin and see if others agree with it. :)
