### ISSUE TITLE
Could not open default.realm

### ISSUE THREAD

**Issue by Wiingaard** [realm/realm-browser-osx#237]
Hello there..

I'm running into this alert when I try to open a realm-file from the iOS-simuletors Documents folder.
<img width="532" alt="skaermbillede 2016-11-22 kl 21 01 21" src="https://cloud.githubusercontent.com/assets/8324312/20539894/1cef725a-b0f7-11e6-9080-22984a08b550.png">

I find the path to the realm file like this:
`print("Realm path: \(Realm.Configuration.defaultConfiguration.fileURL!)")`

Here's the file that I'm trying to open:
[default.realm.zip](https://github.com/realm/realm-browser-osx/files/607482/default.realm.zip)

I have three very basic Objects in the realm.

**I'm using:**
- Realm 2.1.0 (also had the problem on 2.0.4) for iOS via CocoaPods
- Xcode 8.1
- Realm Browser 2.0.1 (79)
**Running on:** iOS-simulator, iPhone 5, iOS 10.1

**Comment by TimOliver** [comment]
Hi @Wiingaard!

I just tried downloading and opening your file there and it worked fine!

![screen shot 2016-11-22 at 6 12 10 pm](https://cloud.githubusercontent.com/assets/429119/20549239/64e73f7e-b0df-11e6-9514-49c7fab08573.png)

I used Realm Browser 2.0.1 from the App Store. How were you opening them exactly? Were you clicking 'Allow' on the sandboxing dialog when it opened?

**Comment by chien** [comment]
@TimOliver 

We're having the similar problem here with this [file](https://dl.dropboxusercontent.com/u/18823852/1479915583.53501.realm)

Any suggestion?

**Comment by Wiingaard** [comment]
Okay, Nice @TimOliver.. Weird that you can open the file. I have done further discoveries in this issue. The problem (for me, at least) seems to be tied to what simulator I'm running on. 
When I use:
- iPhone 5 (10.1): I see the problem, as descriped above
- iPhone 7 (10.1): No problem, I can open the .realm as expected
For now I can like with running on iPhone 7, so I won't dig deeper into this issue.

How I open the files:
1. Run simulator, that creates the realm and prints the path.
2. Use finder (macOS 10.12.1), navigate to the path.
3. Open the "default.realm" file by double clicking and clicking allow on promt from browser.

**Comment by TimOliver** [comment]
@chien Hi Chien! I just tried opening it in a debug build of the Browser and it looks like Realm Core itself is throwing an exception for it. It MIGHT imply that that file has become damaged somehow. Can you please provide some more information on where and how  you got that file?

@Wiingaard Ohhh okay, I know what's going on then.

iPhone 5 is a 32-bit device (ARMv7s) and the iPhone 7 is a 64-bit device (ARM64) and the iOS Simulator simulates these architectures. Because of the difference in architectures, it's not possible to observe a Realm file from the Browser (On a 64-bit Mac) involving 2 different architectures.

I'd recommend staying clear of looking at the iPhone 5 Realm file while the Simulator is running. There's not a lot more we can do at this point.

**Comment by stel** [comment]
@chien looks like this issue is related to core issue https://github.com/realm/realm-core/issues/2289 which was fixed.

**Comment by stel** [comment]
Closing this issue because it seems resolved.

**Comment by chien** [comment]
@stel thanks. yes, the problem seems to be fixed in realm/realm-core#2289. But unfortunately, there is no way to recover the corrupted db file.

**Comment by jpsim** [comment]
> But unfortunately, there is no way to recover the corrupted db file.

Correct. Because corruption can happen in all sorts of surprising ways, with different effects, there's no automatic way to "uncorrupt" or repair a corrupted file. It can be done manually though, by people with expertise about the file format's binary representation and a hex editor and lots of patience though, by identifying areas that don't look right and fixing them manually.
