### ISSUE TITLE
Make better screenshot for App Store & Docs

### ISSUE THREAD

**Issue by timanglade** [realm/realm-browser-osx#49]
The browser itself doesn’t have much UI — it’s all about the data. So if the data is crappy, the browser looks crappy.

Can we make a new screenshot with the following issues fixed?
1. Use real classes with a real schema people can understand
2. Show a model less columns so the screenshot doesn’t look too busy
3. Make sure the data in the column is consistent so the columns look regular (In the current screenshot the first integer column has many orders of magnitude)

**Comment by TimOliver** [comment]
Alrighty. I had a think about this, but let me get confirmation before I spend any cycles on this.

Going with these requirements, I think it would be better if we built a quick sample app to generate a Realm file containing some tightly-controlled, hand-crafted data, instead of relying on randomly generated sample data (Which I explored in the some of the Realm sample apps), or some contextless production data that really requires the parent app to make sense (Briefly considering using my app's own production data).

Following the dogs and their owners motif that is present in a lot of Realm's sample code, shall I create a sample Realm file containing a similar set of demonstration data?

The schema would be as follows:
`Dog` Model Object
* name (String)
* age (Integer)
* Birthdate (NSDate)
* Vaccinated (BOOL)
* Owner (RLMObject)

`Owner` Model Object (Only visible on the classes list)
* name (String)

Let me know what you think! :)

**Comment by timanglade** [comment]
I think having both age + birthdate might be confusing. Usually you’d only store the birthdate and calculate the age, no? Looks good otherwise!

**Comment by TimOliver** [comment]
Normally yes.  But for the sake of demonstrating the capabilities of the Browser, being able to demonstrate the age as an integer value might be beneficial.

Failing that, I'll try and think up another integer value we could potentially advertise. :)

**Comment by jpsim** [comment]
Go for `height` as a Double instead?

**Comment by TimOliver** [comment]
@jpsim Ooh! That's a great idea! Thanks for that! :)

Cool, so assuming no other issues, I'll create a mock Realm file with these pieces of data to use as the screenshot tomorrow. :)

**Comment by TimOliver** [comment]
Alrighty. How's this?

![realmbrowserscreenshot](https://cloud.githubusercontent.com/assets/429119/9004698/df98cd14-37aa-11e5-85bf-60646652aca6.jpg)

**Comment by timanglade** [comment]
Definite improvement! I would ship it. (At some point later on we may want
to add a third model + fill vertical space in the grid). Can you update
this in our docs + on the app store?

**Comment by TimOliver** [comment]
Updated in the both the Realm documentation and the latest App Store submission.
