### ISSUE TITLE
Numeric columns often appear empty

### ISSUE THREAD

**Issue by bdash** [realm/realm-browser-osx#78]
On OS X 10.11, most numeric columns in the browser appear to be empty unless they have very large numbers: 
<img width="783" alt="empty column" src="https://cloud.githubusercontent.com/assets/54825/10110151/4f8be51a-6380-11e5-86d2-3b4ea4dd9488.png">

Manually resizing the column allows the values to become visible:
<img width="783" alt="non-empty column" src="https://cloud.githubusercontent.com/assets/54825/10110156/648bf3f6-6380-11e5-8c90-e7f479d2f5e4.png">

This appears to be an issue with the default width of the numeric table cells being wider than the column that contains them.

Note: I reproduced this using `examples/ios/swift-1.2/Migration/default-v2.realm` from realm-cocoa's repository.

**Comment by TimOliver** [comment]
Thanks a lot for reporting that Mark!
I had a bit of a play with it a few days ago to see what's going on. Turns out that El Capitan must have changed how views are now laid out; the text fields inside the cells are no longer resizing to match the bounds of the cells.

I'm working on a way to fix it!

**Comment by bdash** [comment]
This fix from #88 was merged to master as part of #91. This is fixed in v0.96.1, available at https://github.com/realm/realm-browser-osx/releases and in the App Store in the very near future.
