### ISSUE TITLE
Support Realm 0.96

### ISSUE THREAD

**Issue by amccarri** [realm/realm-browser-osx#84]
Opening a Realm 0.96 database results in error message saying database is encrypted or is not in a compatible file format.

Config:

realm-browser-osx master
Xcode 7
el capitan
Realm 0.96-beta2

**Comment by TimOliver** [comment]
Hi @amccarri!

Sorry about that! With the new NULL support in Realm 0.96, it's introducing a pretty comprehensive file format change as well, which is why it's reporting that it cannot open the file.

I'll create a beta version of the Browser with Realm 0.96 support, but we'll be holding back on an official build with 0.96 until we've implemented a way to ensure developers can explicitly disallow certain Realm files to be upgraded if they're debugging an app with an older build of Realm.

Thanks a lot!

**Comment by TimOliver** [comment]
Okay! Here's a branch that has been updated to use Realm 0.96-beta. You should be able to download it and build it as-is (Make sure to open the workspace as it uses CocoaPods).

https://github.com/realm/realm-browser-osx/tree/0.96-beta

As Realm 0.96 is still in beta, if you discover anything that needs fixing, please let us know!

**Comment by amccarri** [comment]
w00t! thanks! ... I was able to work around by just checkout out the project and updating the Realm pod dependency to 0.96... was going to submit it back to you but you beat me to it. :)

**Comment by TimOliver** [comment]
No worries! Yeah, that was all there was to it in the end. :) Thanks a lot for the offer of the PR though! :)

Let me know if you find any other issues in there!

**Comment by amccarri** [comment]
Will do ... do you have any idea when 0.96 is going to ship?  We really have to have null support, which is why we are targeting Realm 0.96.  Wondering if 0.96 final will be out before our ship date.
